id: P4184714D
initial_creation_type: input
source_metadata:
  title: Khenpo Pema Vajra Series
  language: zh
  description: Texts by and about the Dzogchen scholar Khenpo Pema Vajra (padma badzra,
    c. 1807–1884), also known as Khenpo Pema Dorje.
  volume:
    11f84646475a4e91bf146c8a563a8ea7:
      title: A Liberating Reminder
      parent: Advice
    ae26f854c0a4471db06f737ecb3f4a2b:
      title: The Life of Khenpo Pema Vajra
      parent: Biography
    ccf466fd64294c71b3f9a1c7c52559cd:
      title: A Brief Overview of the Three Turnings and the Mantra Piṭaka of the Vidyādharas
      parent: Commentaries
    88b08fe76c26453a87c5cbf824de8539:
      title: 'Words from the Lineage Masters to Clarify Maitreyanātha''s Vision: An
        Overview of the Perfection of Wisdom''s Ornament of Realization'
      parent: Commentaries
    60c412f986ad4d22b9fc3d75c9f954ab:
      title: A Clear and Concise Description of the Practice of Śamatha
      parent: Meditation
    98641b649f55486f9b71dd3a74c8e910:
      title: Brief Light Offering Prayer
      parent: Prayers
created_at: '2022-03-01T00:26:49.561474'
last_modified_at: '2022-03-01T00:26:49.561477'
